### ISSUE TITLE
neptune mlfow integration not working

### ISSUE THREAD

**Issue by Aid91** [neptune-ml/neptune-mlflow#16]
We encounter some problems with the neptune mlflow --project USER_NAME/PROJECT command. 
I am using a virtual environment setup, with python 3.7, running mlflow (1.0.0) without neptune works, but the integration into neptune-mlflow (0.1.2) gives us the following error:

`(venv) neptune mlflow --project cladler/sandbox
Loading run Default/c93183dbf0a94edfb0a83fa7a66e7c2e
SAN-31
https://ui.neptune.ml/cladler/sandbox/e/SAN-31
Traceback (most recent call last):
  File "/home/cladler/PycharmProjects/firstProject/venv/bin/neptune", line 10, in <module>
    sys.exit(main())
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/neptune_mlflow_plugin/__init__.py", line 26, in sync
    return run_sync(path=path, project=project)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/neptune_mlflow/sync.py", line 45, in sync
    loader.run()
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/neptune_mlflow/data_loader.py", line 51, in run
    exp_uuid = self._create_neptune_experiment(experiment, run)
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/neptune_mlflow/data_loader.py", line 71, in _create_neptune_experiment
    with path_utils.Path(os.path.dirname(run.info.artifact_uri)):
  File "/home/cladler/PycharmProjects/firstProject/venv/lib/python3.7/site-packages/path/__init__.py", line 211, in __enter__
    os.chdir(self)
FileNotFoundError: [Errno 2] No such file or directory: Path('file:///home/cladler/PycharmProjects/firstProject/tutorial-dir/mlruns/0/c93183dbf0a94edfb0a83fa7a66e7c2e')`

Is there a solution for this given problem?

**Comment by aniezurawski** [comment]
Hi @Aid91,

Thanks for your report. The problem occurred because version 1.0.0 of mlflow broke backward compatibility.
Version 0.1.3 of `neptune-mlflow` with a fix for this issue was just released. :)

**Comment by Aid91** [comment]
Hi @aniezurawski,

Great! Thanks a lot for the quick fix :)
